### ISSUE TITLE
Method confusion

### ISSUE THREAD

**Issue by Beknown-J** [habom2310/Heart-rate-measurement-using-camera#10]
Why not using the "video_fps = cap.get(cv2.CAP_PROP_FPS)", but the "fps = float(L) / (times[-1] - times[0])"?
I did not find a paper to describe it like this. 
Looking forward to your help.

**Comment by habom2310** [comment]
In real-time mode, the fps is the actual frames processed every second. For example, because of complicated computation, I can only process 15 frame per sec on my pc, whereas `cap.get(cv2.CAP_PROP_FPS)` will always return 30 fps, which is a property of my pc's camera. Therefore, if I calculate the fft with that 30 fps, the result will be wrong because I can actually get 15 frames per second. That's why I use `fps = float(L) / (times[-1] - times[0])` there.

In contrast, the `cap.get(cv2.CAP_PROP_FPS)` is for video mode.

**Comment by Beknown-J** [comment]
Thank you. This is very helpful to me.
